import { MouseDriverRes } from '../types/mouseDriverView/res/mouseDriverViewRes';
import {
  ajazz,
  akko,
  atk,
  attackShark,
  aula,
  bloodyGaming,
  coolerMaster,
  corsair,
  cougar,
  dareu,
  darmoshark,
  delux,
  endgameGear,
  finalmouse,
  fnatic,
  gWolves,
  glorious,
  gravaStar,
  hitscan,
  hyperX,
  incott,
  ipi,
  irocks,
  keychron,
  lamzu,
  logitechG,
  madLions,
  mchose,
  monka,
  ninjutso,
  nzxt,
  pulsar,
  rapoo,
  razer,
  rog,
  steelseries,
  tuf,
  turtleRoccat,
  unius,
  valkyrie,
  vancer,
  vaxee,
  vgn,
  waizowl,
  wlmouse,
  xtrfy,
} from './detailsData';

export const mouseDriverData: MouseDriverRes[] = [
  {
    img: 'images/Lamzu.jpg',
    englishName: 'Lamzu',
    chineseName: '蘭族',
    website: 'https://lamzu.com/',
    details: lamzu,
  },
  {
    img: 'images/Ninjutso.jpg',
    englishName: 'Ninjutso',
    chineseName: '',
    website: 'https://ninjutso.com/',
    details: ninjutso,
  },
  {
    img: 'images/Ajazz.jpg',
    englishName: 'Ajazz',
    chineseName: '黑爵',
    website: 'https://www.a-jazz.com/',
    details: ajazz,
  },
  {
    img: 'images/BloodyGaming.png',
    englishName: 'Bloody Gaming',
    chineseName: '血手幽靈',
    website: 'https://a4bloody.cyberbiz.co/',
    details: bloodyGaming,
  },
  {
    img: 'images/CoolerMaster.jpg',
    englishName: 'CoolerMaster',
    chineseName: '酷碼',
    website: 'https://www.coolermaster.com/zh-tw/',
    details: coolerMaster,
  },
  {
    img: 'images/Corsair.png',
    englishName: 'Corsair',
    chineseName: '海盜船',
    website:
      'https://www.corsair.com/tw/zh?srsltid=AfmBOoo7OdEARLzFFQ-3sUuHfY31yjfMjX9vZB5f5gNUGK6op5Gtgmfm',
    details: corsair,
  },
  {
    img: 'images/LogitechG.png',
    englishName: 'Logitech G',
    chineseName: '羅技',
    website: 'https://www.logitechg.com/zh-tw',
    details: logitechG,
  },
  {
    img: 'images/Cougar.png',
    englishName: 'Cougar',
    chineseName: '美洲獅',
    website: 'https://cougargaming.com/tw/',
    details: cougar,
  },
  {
    img: 'images/EndgameGear.png',
    englishName: 'Endgame Gear',
    chineseName: '',
    website: 'https://www.endgamegear.com/en-us/',
    details: endgameGear,
  },
  {
    img: 'images/Finalmouse.png',
    englishName: 'Finalmouse',
    chineseName: '',
    website: 'https://finalmouse.com/',
    details: finalmouse,
  },
  {
    img: 'images/Fnatic.png',
    englishName: 'Fnatic',
    chineseName: '',
    website: 'https://fnatic.com/gear',
    details: fnatic,
  },
  {
    img: 'images/G-Wolves.png',
    englishName: 'G - Wolves',
    chineseName: '遊狼',
    website: 'https://shop.g-wolves.com/',
    details: gWolves,
  },
  {
    img: 'images/Glorious.png',
    englishName: 'Glorious',
    chineseName: '',
    website:
      'https://www.gloriousgaming.com/?srsltid=AfmBOopPRe_yRgDNUllohOcikYMcDUdXdMwILsdaqP1rW2Vi-Ob6JKxo',
    details: glorious,
  },
  {
    img: 'images/Hitscan.png',
    englishName: 'Hitscan',
    chineseName: '',
    website:
      'https://hitscan.com/?srsltid=AfmBOorCv_hbkE_o8YcS1Vcsin3bsagQQn9B5UQljUtkby4uOD0bX_4u',
    details: hitscan,
  },
  {
    img: 'images/HyperX.png',
    englishName: 'HyperX',
    chineseName: '',
    website: 'https://row.hyperx.com/zh-tw/',
    details: hyperX,
  },
  {
    img: 'images/Incott.png',
    englishName: 'Incott',
    chineseName: '因科特',
    website: 'http://www.szironcat.com/',
    details: incott,
  },
  {
    img: 'images/IPI.png',
    englishName: 'IPI',
    chineseName: '',
    website: '',
    details: ipi,
  },
  {
    img: 'images/Irocks.png',
    englishName: 'Irocks',
    chineseName: '艾芮克',
    website: 'https://www.i-rocks.com.tw/web/index/index.jsp',
    details: irocks,
  },
  {
    img: 'images/NZXT.png',
    englishName: 'NZXT',
    chineseName: '恩傑',
    website:
      'https://nzxt.com/?srsltid=AfmBOor8NQB1QmiLkdmf1EbmhDDcTtzNtPT_gVSR-PR1xhRkfGNZ2gHG',
    details: nzxt,
  },
  {
    img: 'images/Pulsar.png',
    englishName: 'Pulsar',
    chineseName: '派世',
    website: 'https://www.pulsar.gg/',
    details: pulsar,
  },
  {
    img: 'images/TurtleRoccat.png',
    englishName: 'TurtleBeach & Roccat',
    chineseName: '烏龜海灘',
    website:
      'https://www.turtlebeach.com/?srsltid=AfmBOoppVCpYjrzrl8ostd0aCtna4O9d7zQOgyNo-WBYbmLPUM1dLjuz',
    details: turtleRoccat,
  },
  {
    img: 'images/ROG.png',
    englishName: 'ROG',
    chineseName: '華碩',
    website: 'https://rog.asus.com/tw/',
    details: rog,
  },
  {
    img: 'images/TUF.png',
    englishName: 'TUF',
    chineseName: '華碩',
    website: 'https://www.asus.com/campaign/tuf-gaming/tw/',
    details: tuf,
  },
  {
    img: 'images/Steelseries.png',
    englishName: 'Steelseries',
    chineseName: '賽睿',
    website: 'https://tw.steelseries.com/',
    details: steelseries,
  },
  {
    img: 'images/Unius.png',
    englishName: 'Unius',
    chineseName: '',
    website: 'https://www.un1us.com/',
    details: unius,
  },
  {
    img: 'images/Vancer.png',
    englishName: 'Vancer',
    chineseName: '',
    website: 'https://www.vancer.gg/',
    details: vancer,
  },
  {
    img: 'images/Vaxee.png',
    englishName: 'Vaxee',
    chineseName: '',
    website: 'https://www.vaxee.co/zh-hant/',
    details: vaxee,
  },
  {
    img: 'images/VGN.png',
    englishName: 'VGN',
    chineseName: '',
    website: 'https://vgnlab.com/',
    details: vgn,
  },
  {
    img: 'images/Waizowl.png',
    englishName: 'Waizowl',
    chineseName: '唯卓',
    website: 'https://waizowl.com/zh-hant',
    details: waizowl,
  },
  {
    img: 'images/WLmouse.png',
    englishName: 'WLmouse',
    chineseName: '萬靈',
    website:
      'https://www.wlmouse.com/?srsltid=AfmBOophC-4-0ePkK5HVDGoHL2U0aghj4WPxubhgVrTNfqPzey15r6kM',
    details: wlmouse,
  },
  {
    img: 'images/Keychron.png',
    englishName: 'Keychron',
    chineseName: '渴創',
    website:
      'https://www.keychron.com.tw/?srsltid=AfmBOoqnjdu8ul2SyCfXtEFCusHgxuzxVBAiTAer4amJO9R71sgs2Gtf',
    details: keychron,
  },
  {
    img: 'images/Darmoshark.png',
    englishName: 'Darmoshark',
    chineseName: '達摩鯊',
    website: 'https://www.darmosharkgear.com/',
    details: darmoshark,
  },
  {
    img: 'images/Monka.png',
    englishName: 'Monka',
    chineseName: '魔咖',
    website: 'https://monka.gg/',
    details: monka,
  },
  {
    img: 'images/MCHOSE.png',
    englishName: 'MCHOSE',
    chineseName: '邁從',
    website: 'https://www.mchose.store/',
    details: mchose,
  },
  {
    img: 'images/Rapoo.png',
    englishName: 'Rapoo',
    chineseName: '雷柏',
    website: 'https://www.rapoo-eu.com/',
    details: rapoo,
  },
  {
    img: 'images/XTRFY.png',
    englishName: 'XTRFY',
    chineseName: '',
    website: 'https://cherryxtrfy.com/',
    details: xtrfy,
  },
  {
    img: 'images/ATTACK SHARK.png',
    englishName: 'ATTACK SHARK',
    chineseName: '攻擊鯊',
    website:
      'https://attackshark.com/?srsltid=AfmBOooIa3FW0x060v_7vEllnJdDzypUEVqm06mjriGQzt_nTMGYyWjP',
    details: attackShark,
  },
  {
    img: 'images/VALKYRIE.png',
    englishName: 'VALKYRIE',
    chineseName: '瓦爾基里',
    website: 'https://www.valkyrie.com.cn/#/',
    details: valkyrie,
  },
  {
    img: 'images/Razer.png',
    englishName: 'Razer',
    chineseName: '雷蛇',
    website:
      'https://www.razer.com/tw-zh?srsltid=AfmBOopbPMMAhdp8sZPph3784a17LcO6lFNlWxMFZQwRAghjU6jY9PQt',
    details: razer,
  },
  {
    img: 'images/Delux.png',
    englishName: 'Delux',
    chineseName: '多彩',
    website: 'https://www.deluxworld.com/',
    details: delux,
  },
  {
    img: 'images/ATK.png',
    englishName: 'ATK',
    chineseName: '',
    website:
      'https://www.atk.store/?srsltid=AfmBOoo4EATjO7FkhIdegmohNNAx_HbEh-gCFKWIZJxeiUQPwDmATtNd',
    details: atk,
  },
  {
    img: 'images/MADLIONS.png',
    englishName: 'MADLIONS',
    chineseName: '美加獅',
    website: 'https://madlionskeyboard.com/',
    details: madLions,
  },
  {
    img: 'images/Akko.png',
    englishName: 'Akko',
    chineseName: '艾酷',
    website: 'https://www.akkogear.com/',
    details: akko,
  },
  {
    img: 'images/AULA.png',
    englishName: 'AULA',
    chineseName: '狼蛛',
    website: 'https://www.aulacn.com/',
    details: aula,
  },
  {
    img: 'images/Dareu.png',
    englishName: 'Dareu',
    chineseName: '達爾優',
    website:
      'https://dareu.com/en-eu?srsltid=AfmBOoqlHPxcutq-FISd244DGUIkCnqq4Vxj4V3OQKO9qSVgP0G_CTtK',
    details: dareu,
  },
  {
    img: 'images/GravaStar.png',
    englishName: 'GravaStar',
    chineseName: '重力星球',
    website:
      'https://www.gravastar.com/?srsltid=AfmBOopPKwyJh1SvWeDNiZ1mTVNObqTxgryXhBQdVvLEE8BDMjZV-Aer',
    details: gravaStar,
  },
];
