import { DownLoadDataRes } from '../types/mouseDriverView/res/mouseDriverViewRes';

export const lamzuDownLoad: DownLoadDataRes = {
  downloadDriverUrl:
    'https://lamzu.com/pages/download?srsltid=AfmBOoqn-vbEhqAn4GgWbRf8C2CZZqKZac_is0IOJq4GOeqQlZFUuXKv',
  downloadMouseList: [
    'Atlantis OG V1 & V2',
    'Atlantis OG V2 PRO',
    'Atlantis OG V2 4K',
    'Atlantis MINI',
    'Atlantis MINI PRO',
    'Atlantis MINI 4K',
    'Atlantis MINI Champion Edition',
    'THORN(4K Compatible)',
    'THORN 4K',
    'LAMZU X FNATIC THORN 4K',
    'MAYA(4K Compatible)',
    'MAYA 4K',
    'MAYA Doodle',
    'LAMZU X FNATIC MAYA 8K',
    'LAMZU X FNATIC MAYA X 8K',
    'MAYA X 8K',
    'Paro',
    'Tachi',
    'Inca',
    'Atlantis OG V1 & V2',
    'Atlantis OG V2 PRO',
    'Atlantis OG V2 4K',
    'Atlantis MINI',
    'Atlantis MINI PRO',
    'Atlantis MINI 4K',
    'Atlantis MINI Champion Edition',
    'THORN(4K Compatible)',
    'THORN 4K',
    'LAMZU X FNATIC THORN 4K',
    'MAYA(4K Compatible)',
    'MAYA 4K',
    'MAYA Doodle',
    'LAMZU X FNATIC MAYA 8K',
    'LAMZU X FNATIC MAYA X 8K',
    'MAYA X 8K',
    'Paro',
    'Tachi',
    'Inca',
  ],
  downloadKeyboardList: [],
};
export const ninjutsoDownLoad: DownLoadDataRes = {
  downloadDriverUrl: 'https://ninjutso.com/pages/download',
  downloadMouseList: ['Sora', 'Sora 4K'],
  downloadKeyboardList: [],
};
export const ajazzDownLoad: DownLoadDataRes = {
  downloadDriverUrl:
    'https://download.s21i.co99.net/25789609/0/0/ABUIABBPGAAgi5fd-QUowqjU7QQ.zip?f=AJAZZ_%E4%B8%89%E5%90%88%E4%B8%80_%E5%A5%97%E8%A3%85%E9%A9%B1%E5%8A%A8.zip&v=1605847948',
  downloadMouseList: [
    '蜻蜓點水',
    '青蜂俠 II',
    'Q7',
    'Q7 烈焰版',
    'GT 流光版小蒼版',
    'GT 普通版',
    'GT',
    'GTC',
    'GTi',
    'GTX',
    'AJ100S',
    'AJ110S',
    'AJ110',
    'AJ302 Pro',
    'AJ100',
    'I303Pro',
    'I303Pro 雙模',
    'AJ358',
    'AJ330',
    'AJ302 Pro',
    'AJ332 巧克力',
    'AJ307',
    'AJ118',
    'AJ203',
    'AJ125',
    'AJ117',
    'AJ118 Pro',
    'I380Pro',
    'I380Pro 雙模',
    'AJ52',
    'AJ52 迷彩版',
    'AJ119',
    'AJ120',
    'AJ129',
    'AJ339',
    'AJ380',
    'AJ337',
    'AJ390',
    'AJ390R',
    'AJ380R',
    'AJ903',
    'I339PRO',
    'I309PRO',
    '熱血魔域 x 黑爵',
    'AJ219',
    'AJ199',
    'AJ52 PRO',
    'AJ039',
    'AJ199',
    'AJ199 PRO',
    'AJ139',
    'AJ139 PRO',
    'AJ139 MAX',
    'AJ099',
    'AM3 PRO',
    'AJ199 MAX',
    'M259',
    'AM3 MAX',
    'AJ139 PRO',
    'AJ139 V2 MAX',
    'AJ159',
    'AJ159 PRO',
    'AJ159 APEX',
    'AJ159P',
    'AJ179',
    'AJ179 PRO',
    'AJ179 APEX',
    'AJ179 V2',
    'AJ179 V2 MAX',
    'AJ199',
    'AJ099 PRO',
  ],
  downloadKeyboardList: [
    'AK33',
    'AK33 雙模',
    '黑爵 Chocolate cubes',
    '毛茸茸',
    '蜻蜓點水',
    'AK43',
    'AK60-RGB',
    'AK33-RGB',
    'Zero 原點',
    'K680T',
    'K840T',
    'AK 榮耀王者',
    'AK816',
    'AK535',
    'AK636',
    'AK500',
    'AK525',
    'AK60 RGB',
    'AK45 RGB',
    'AK60 CHERRY',
    'AK48 Plus',
    'AK40S',
    'AK35',
    'AK816Pro',
    'AC067',
    'AC064',
    'AK35i Pro',
    'AC081',
    'AK510 RGB',
    'AK40S RGB',
    'AK40 Pro',
    'AK515',
    'AK535',
    'AK535R',
    'AK535 巧克力方塊版',
    'AK535 蜻蜓點水版',
    'AK666',
    'K610T',
    'AK678',
    'K870T 雙模',
    'K870T RGB',
    'K690T RGB 三模',
    'K685T RGB 三模',
    'AK35',
    'K620T RGB',
    'K690T Pro',
    'K870T PRO',
    'AK873',
    'AK687',
    'AK515',
    'AK873 PRO 三模',
    'AK832 Pro 三模',
    'AK832 三模',
    'AK687 雙模',
    'AK992',
    'AK40 Pro',
    'AK35I',
    'AK35I 三模',
    'AKC087 三模',
    'AC067',
    'AC067 三模',
    'AK692 三模',
    'AK992 三模',
    'AK966 RGB 三模',
    'AK820',
    'AK820 RGB',
    'AK680',
    'AC100',
    'AC100MAX 三模',
    'AC100MAX 三模 RGB',
    'AKS068',
    'AKS068 RGB',
    'AKS068 三模 RGB',
    'AK870',
    'AK870MC',
    'AK870 三模',
    'AK75PRO 三模',
    'AK980',
    'AK35I V3',
    'AK35I V3 RGB',
    'AK35I PRO V2',
    'AK35I PRO V3',
    'QS87 三模',
    'AK820 MAX',
    'AK820 MAX 三模',
    'AK820 MAX PLUS',
    'AK820 MAX PLUS 三模',
    'AK680 MAX',
    'AK820 Pro 三模',
    'AK980 三模',
    'AK650 三模',
    'AKS075 三模',
    'AK870 PLUS 三模',
    'AK680MAX',
    'AK680MAX 三模',
    'AK680MAX RGB 三模',
    'ALUX68',
    'ALUX68 MAX',
    'ALUX68 PLUS',
    'AKP846',
  ],
};
export const bloodyGamingDownLoad: DownLoadDataRes = {
  downloadDriverUrl: 'https://www.bloody.com/tw/download.php?id=6',
  downloadMouseList: [
    'R72 Pro Duo',
    'R72 Ultra Duo',
    'R80',
    'P91 Pro',
    'W95 Max',
    'W95 Max Naraka',
    'W70 MAX',
    'L65 Max Naraka',
    'W60 Max',
    'L65 Max',
    'J95S',
    'J90s',
    'P93',
    'P85S',
    'A91',
    'A90',
    'A70',
    'A60',
    'V8M',
    'V7M',
    'V5M',
    'T70',
    'T60',
    'T50',
    'TL80',
    'TL60',
    'TL50',
    'ZL50',
    'ML160',
    'RT62',
    'TL90',
    'R70',
    'AL90',
    'V3M',
    'V4M',
    'RT50',
    'RT70',
    'R30',
    'N50',
    'TL70',
    'P81',
    'P87',
    'P88',
  ],
  downloadKeyboardList: [
    'B740A',
    'B720',
    'B700',
    'B418',
    'B500N',
    'B328',
    'B318',
    'B120',
    'B845R',
    'S510N',
    'B254',
    'B2100',
    'B860',
    'B188',
    'B314',
    'B740S',
    'B830',
    'B1500',
  ],
};
export const coolerMasterDownLoad: DownLoadDataRes = {
  downloadDriverUrl: 'https://www.coolermaster.com/zh-tw/masterplus/',
  downloadMouseList: [
    'MM310 SF6 春麗',
    'MM712 LINE FRIENDS minini / 30 週年紀念版 / 黑 / White',
    'MM731 黑 / 白',
    'MM730 黑 / 白',
    'MM311 黑 / 白',
    'MM310 黑 / 白',
    'MM711 金色 / 金屬藍 / 荒野 / 黑',
    'MM710',
    'MM831',
    'MM830',
    'MM720',
  ],
  downloadKeyboardList: [
    'CK570 SF6 春麗',
    'CK721 LINE FRIENDS minini',
    'SK653 黑 / 白',
    'SK652 黑 / 白',
    'SK622 太空灰 / 太空銀',
    'CK530 V2 / CK550 V2 / CK351',
    'MK850',
  ],
};
export const corsairDownLoad: DownLoadDataRes = {
  downloadDriverUrl:
    'https://www.corsair.com/tw/tw/s/downloads?srsltid=AfmBOoq2xs91_R4slEHoiixpO2FY7-ZxMkG7uTl1GiYzOEU9RROSiEJx',
  downloadMouseList: [
    'Sabre',
    'Sabre RGB',
    'Sabre RGB Optical',
    'Sabre RGB Laser',
    'Sabre Pro Champion',
    'Sabre RGB Pro Champion',
    'Scimitar RGB',
    'Scimitar RGB Pro',
    'Scimitar RGB Elite',
    'Glaive RGB',
    'Glaive RGB PRO',
    'Dark Core RGB',
    'Dark Core SE',
    'Dark Core PRO',
    'Dark Core PRO SE',
    'M55',
    'M55 WIRELESS',
    'M75 WIRELESS Call of Duty Black Ops 6',
    'M65 RGB',
    'M65 RGB PRO',
    'M65 RGB Elite',
    'M65 RGB Elite IG',
    'M65 RGB ULTRA',
    'M65 RGB ULTRA WIRELESS',
    'M75 AIR',
    'M75 LIGHTWEIGHT',
    'M75 WIRELESS',
    'Ironclaw RGB',
    'Ironclaw RGB WIRELESS',
    'Nightsword RGB',
    'Harpoon RGB',
    'Harpoon RGB WIRELESS',
    'Harpoon RGB PRO',
    'M55 RGB PRO',
    'Katar',
    'Katar PRO',
    'Katar PRO WIRELESS',
    'Katar PRO XT',
    'Katar RGB',
  ],
  downloadKeyboardList: [
    'K100 RGB',
    'K100 AIR',
    'K95',
    'K95 RGB Platinum',
    'K95 RGB Platinum SE',
    'K95 RGB Platinum XT',
    'K70 RGB TKL',
    'K70 RGB MK.2',
    'K70 MK.2 LP',
    'K70 MK.2 SE',
    'K70 RGB MK.2 IG',
    'K65 RGB Mini',
    'K65 PLUS WIRELESS TACTILE',
    'K83 WIRELESS',
    'K70 RGB',
    'K70 RGB PRO',
    'K70 Lux RGB',
    'K70 RGB Rapidfire',
    'K70 RGB SE Rapidfire',
    'K70 Lux',
    'K70 Rapidfire',
    'K70 PRO MINI',
    'K70 CORE SE RGB',
    'K70 PRO TKL',
    'K70 CORE TKL',
    'K70 CORE TKL WIRELESS',
    'Strafe',
    'Strafe RGB 和 Strafe MX',
    'Strafe RGB MK.2',
    'K68',
    'K68 RGB 和 K68 SE',
    'K66',
    'K65 RGB',
    'K65 Lux RGB',
    'K65 RGB Rapidfire',
    'K65 PLUS WIRELESS Call of Duty Black Ops 6',
    'K63',
    'K63 WIRELESS',
    'K60 PRO',
    'K60 RGB PRO',
    'K60 RGB PRO SE',
    'K60 RGB PRO LP',
    'K60 PRO TKL RGB',
    'K57 RGB WIRELESS',
    'K55 RGB',
    'K55 RGB PRO',
    'K55 RGB PRO XT',
    'K55 RGB PRO LITE',
    'K55 CORE RGB',
  ],
};
export const logitechGDownLoad: DownLoadDataRes = {
  downloadDriverUrl: 'https://www.logitechg.com/zh-tw/innovation/g-hub.html',
  downloadMouseList: [
    'PRO X SUPERLIGHT 2 DEX',
    'PRO 2 LIGHTSPEED',
    'G309 LIGHTSPEED',
    'Pro XSUPERLIGHT 2',
    'G502 X PLUS',
    'G705',
    'PRO X',
    'G502 X LIGHTSPEED',
    'G PRO Wireless',
    'G502 X',
    'G502',
    'G304',
    'G502',
    'G502 HERO',
    'G903',
    'G703',
    'G102',
    'G403',
    'G403 HERO',
    'G102',
  ],
  downloadKeyboardList: [
    'PRO X TKL RAPID',
    'G515 TKL',
    'G915 X LIGHTSPEED',
    'G915 X LIGHTSPEED TKL',
    'G915 X',
    'G913 TKL',
    'G515 LIGHTSPEED TKL',
    'PRO X 60',
    'PRO X TKL',
    'G715',
    'G913',
    'PRO X',
    'G713',
    'G512',
    'G213',
    'G PRO',
    'G413 SE',
    'G813',
  ],
};
export const cougarDownLoad: DownLoadDataRes = {
  downloadDriverUrl: 'https://cougargaming.com/tw/downloads/',
  downloadMouseList: [
    'AIRBLADER',
    'DUALBLADER',
    '700M EVO',
    '700M',
    '700M Superior',
    '700M eSPORTS',
    'Revenger ST',
    'Revenger S',
    'MINOS XT',
    'MINOS XC',
    'MINOS X5',
    'Revenger',
    'SURPASSION ST',
    'SURPASSION',
    'MINOS X3',
    '600M',
    '600M eSPORTS',
    '550M',
    '530M',
    '500M',
    '450M',
    '400M',
    '300M',
    '250M',
  ],
  downloadKeyboardList: [
    'VANTAR MX',
    '700K EVO',
    'PURI RGB',
    'PURI TKL RGB',
    'ATTACK X3 RGB SPEEDY',
    'Attack X3 RGB',
    '700K',
    '600K',
    '500K',
    '450K',
    '300K',
    'ATTACK X3',
  ],
};
export const endgameGearDownLoad: DownLoadDataRes = {
  downloadDriverUrl: 'https://www.endgamegear.com/en-us/downloads',
  downloadMouseList: [
    'OP1',
    'OP1w 4k',
    'OP1 8k',
    'OP1 8k Purple Frost Limited Edition',
    'OP1 RGB',
    'OP1we',
    'XM2 8k',
    'XM2w 4k',
    'XM2we',
    'XM1R',
    'XM1 RGB',
    'XM1',
  ],
  downloadKeyboardList: ['KB65HE'],
};
export const finalmouseDownLoad: DownLoadDataRes = {
  downloadDriverUrl: '',
  downloadMouseList: [],
  downloadKeyboardList: [],
};
export const fnaticDownLoad: DownLoadDataRes = {
  downloadDriverUrl: 'https://fnatic.com/gear/op',
  downloadMouseList: ['BOLT - White', 'BOLT - Black'],
  downloadKeyboardList: [
    'STREAK80 LP - White US ANSI',
    'STREAK65 LP - Black',
    'STREAK65 LP - White',
    'STREAK65',
    'MiniStreak Speed',
    'MiniStreak Silent',
  ],
};
export const gWolvesDownLoad: DownLoadDataRes = {
  downloadDriverUrl:
    'https://shop.g-wolves.com/pages/driver-software-for-g-wolves-wireless-mouse',
  downloadMouseList: [
    'Fenrir Asym 8K Wireless',
    'Fenris Max 8K Wireless',
    'Hati-M HTM ACE Wireless',
    'Hati-S ACE Wireless',
    'Hati-S OPEN Source Wireless',
    'G-wolves HSK Plus ( HSK+ ) 4K Wireless',
    'HSK Pro 4K Wireless',
    'HSK Pro ACE Wireless',
    'HT-S2 8K Wireless',
    'HT-S2 Pro 8K Wireless',
    'HTR 8K Wireless',
    'HTR Pro 8K Wireless',
    'HSK Plus ( HSK+ ) Lite Wireless',
    'HTS Plus (HTS+) 4K Wireless',
    'HTS Plus ( HTS+ ) ACE Wireless',
    'HTS Plus 8K Wireless',
    'HTS Ultra 8K Wireless',
    'HTX 4K',
    'HTX ACE',
    'HTX Mini 8K',
  ],
  downloadKeyboardList: [],
};
export const gloriousDownLoad: DownLoadDataRes = {
  downloadDriverUrl:
    'https://www.gloriousgaming.com/pages/software?srsltid=AfmBOoraWC8bWA-7zFy-J6awiLHYJ5-2-EoRYWpNdOFe6w4Cp6FvkGCF',
  downloadMouseList: [
    'Model O 2',
    'Model O 2 Mini Wireless',
    'Model O 2 Wireless',
    'Model O 2 PRO Series Wireless',
    'Model D 2',
    'Model D 2 Wireless',
    'Model D 2 PRO Series Wireless',
    'Model I 2 Wireless',
    'Series 2 PRO Wireless',
  ],
  downloadKeyboardList: [
    'GMMK 2',
    'GMMK 3 Prebuilt',
    'GMMK 3 PRO Prebuilt Wireless',
    'GMMK 3 HE Prebuilt',
    'GMMK 3 PRO Prebuilt',
    'GMMK 3 PRO HE Prebuilt Wireless',
    'GMMK 3 PRO HE Prebuilt',
    'GMMK PRO Prebuilt 75%',
  ],
};
export const hitscanDownLoad: DownLoadDataRes = {
  downloadDriverUrl:
    'https://hitscan.com/pages/download?srsltid=AfmBOoob0TdvQPN422rqZ7y5ZvY9kfqYMa72mzOwIfrL2--GhltEPqQ0',
  downloadMouseList: ['HYPERLIGHT'],
  downloadKeyboardList: [],
};
export const hyperXDownLoad: DownLoadDataRes = {
  downloadDriverUrl: 'https://row.hyperx.com/zh-tw/pages/ngenuity',
  downloadMouseList: [
    'Pulsefire Haste 2 S Wireless',
    'Pulsefire Haste 2 Pro',
    'Pulsefire Haste 2 Core Wireless',
    'Pulsefire Haste 2 Mini Wireless',
    'Pulsefire Haste 2',
    'Pulsefire Haste 2 Wireless',
    'Pulsefire Core',
    'Pulsefire Haste',
    'Pulsefire Haste Wireless',
    'Pulsefire Surge',
    'Pulsefire Dart',
    'Pulsefire Raid',
    'Pulsefire FPS Pro',
  ],
  downloadKeyboardList: [
    'Alloy Rise 75 Wireless',
    'Alloy Rise 75',
    'Alloy Origins 60',
    'Alloy Rise',
    'Alloy Origins Core',
    'Alloy MKW100',
    'Alloy Origins',
    'Alloy Elite 2',
    'Alloy Origins 65',
  ],
};
export const incottDownLoad: DownLoadDataRes = {
  downloadDriverUrl: '',
  downloadMouseList: [],
  downloadKeyboardList: [],
};
export const ipiDownLoad: DownLoadDataRes = {
  downloadDriverUrl: 'https://share.weiyun.com/ZxkJvkZc',
  downloadMouseList: ['飄 11', '飄 18', '飄 88'],
  downloadKeyboardList: [],
};
export const irocksDownLoad: DownLoadDataRes = {
  downloadDriverUrl:
    'https://www.i-rocks.com.tw/web/service/download_list_in.jsp?cp_id=CP1692864414368',
  downloadMouseList: [
    'M23R',
    'M29R Wireless',
    'M31R Wireless',
    'M31R',
    'M49R Wireless',
    'M09 Plus',
    'M36 Pro',
    'M36 Pure',
    'M39 Pro',
    'M40E',
  ],
  downloadKeyboardList: [
    'K104H',
    'K60M RGB',
    'K70E',
    'K72MK',
    '72MN',
    'K76M Costom',
    'K76M PLUS',
    'K50W Plus',
    'K59M',
    'K68MNF',
    'K68MSF',
    'K27WF',
    'K69M',
    'K71M',
    'K73M',
    'K74M',
    'K89M',
    'K103R',
    'K46BR',
    'K71R',
    'K74R',
    'K85R',
    'K86R',
  ],
};
export const nzxtDownLoad: DownLoadDataRes = {
  downloadDriverUrl:
    'https://nzxt.com/software/cam?srsltid=AfmBOor5INbCM5ansDj4dZoQqhYWnbD7SmzgROXo0505syHu6HllWGX0',
  downloadMouseList: [
    'Lift Elite Wireless',
    'Lift 2 Ergo',
    'Lift 2 Symm',
    'Lift (White)',
    'Lift 2 Starfield',
  ],
  downloadKeyboardList: [
    'Function Elite MiniTKL',
    'Function 2 MiniTKL',
    'Function 2',
  ],
};
export const pulsarDownLoad: DownLoadDataRes = {
  downloadDriverUrl: 'https://www.pulsar.gg/pages/download',
  downloadMouseList: [
    'Xlite v4 eS',
    'Xlite v4 Mini',
    'Xlite v4',
    'Xlite v4 Large',
    'Xlite v4 - Quiccs Edition',
    'Xlite v4 Mini - Quiccs Edition',
    'Xlite v3 eS',
    'Xlite v3 Large',
    'Xlite v3 Medium',
    'Xlite v3 Mini',
    'Xlite v2',
    'Xlite v2 Mini',
    'Xlite Wired',
    'Xlite Wired (2021)',
    'X2 CrazyLight',
    'X2 v3',
    'X2 v2',
    'X2 v2 Mini',
    'X2 v1 Mini',
    'X2 v1',
    'X2 Wired',
    'X2H v3 Mini',
    'X2H v3',
    'X2H eS',
    'X2H',
    'X2H Mini',
    'X2H Wired',
    'X2A eS',
    'X2A',
    'X2A Mini',
    'X2A Wired',
    'X2A v3',
    'X3',
    'X3 Mini',
    'X3 LHD',
    'X3 LHD Mini',
    'Feinmann F01',
  ],
  downloadKeyboardList: [
    'XBOARD MS',
    'XBOARD QS',
    'PCMK 2 HE TKL',
    'Nova Optical Pro',
    'PCMK TKL',
    'PCMK 60%',
  ],
};
export const turtleRoccatDownLoad: DownLoadDataRes = {
  downloadDriverUrl:
    'https://support.turtlebeach.com/s/downloads?language=en_US#/319/Swarm-II',
  downloadMouseList: [
    'Burst II Air',
    'Kone II',
    'Kone II Air',
    'Roccat Kone XP Air',
    'Kone XP Air',
    'Pure Air',
    'Pure SEL',
  ],
  downloadKeyboardList: [
    'Roccat Magma',
    'Magma',
    'Roccat Vulcan II',
    'Vulcan II',
    'Roccat Vulcan II Max',
    'Vulcan II Max',
    'Roccat Vulcan II Mini',
    'Vulcan II Mini',
    'Roccat Vulcan II Mini Air',
    'Vulcan II Mini Air',
    'Vulcan II TKL Pro',
    'Roccat Vulcan TKL AIMO',
    'Vulcan TKL AIMO',
  ],
};
export const rogDownLoad: DownLoadDataRes = {
  downloadDriverUrl: 'https://rog.asus.com/tw/content/armoury-crate/',
  downloadMouseList: [
    'Harpe Ace Mini Wireless',
    'Harpe Ace Extreme Wireless',
    'Keris II Ace',
    'Strix Impact III Wireless',
    'Gladius III Wireless AimPoint EVA-02',
    'Chakram X Origin',
    'Harpe Ace Aim Lab Edition',
    'Strix Impact III',
    'Keris Wireless AimPoint',
    'Gladius III Wireless AimPoint Wireless',
    'Keris Wireless EVA Wireless',
    'Chakram X Wireless',
    'Strix Impact II Moonlight White',
    'Spatha X',
    'Gladius III Wireless',
    'Gladius III',
    'Strix Impact II GUNDAM',
    'Strix Impact II Electro Punk',
    'Pugio II',
    'Pugio',
    'Strix Impact II',
    'Gladius II Origin',
    'Gladius II Core',
    'Strix Carry',
  ],
  downloadKeyboardList: [
    'Falchion Ace HFX',
    'Strix Scope II 96 RX Wireless',
    'Azoth Extreme',
    'Falchion RX Low Profile',
    'Strix Scope RX EVA-02',
    'Strix Scope II RX',
    'Strix Scope II',
    'Strix Scope II 96 Wireless',
    'Azoth Wireless',
    'Falchion Ace',
    'Strix Scope RX EVA',
    'Strix Scope NX Wireless Deluxe',
    'Strix Scope RX TKL Wireless Deluxe',
    'Strix Flare II',
    'Strix Flare II Animate',
    'Strix Scope NX TKL Moonlight White',
    'Strix Scope NX TKL',
    'Strix Scope NX',
    'Falchion NX',
    'Claymore II',
    'Strix Scope TKL GUNDAM',
    'Strix Scope RX',
    'Falchion',
    'Strix Scope TKL Electro Punk',
    'Strix Scope TKL Deluxe',
    'Strix Scope PBT',
    'Strix Scope',
  ],
};
export const tufDownLoad: DownLoadDataRes = {
  downloadDriverUrl: 'https://rog.asus.com/tw/content/armoury-crate/',
  downloadMouseList: [
    'Gaming M3 Gen II',
    'Gaming M3',
    'Gaming M4 Air',
    'Gaming M4',
  ],
  downloadKeyboardList: ['Gaming K3 Gen II', 'Gaming K3'],
};
export const steelseriesDownLoad: DownLoadDataRes = {
  downloadDriverUrl: 'https://tw.steelseries.com/gg/engine',
  downloadMouseList: [
    'Rival 3',
    'Rival 3 Wireless',
    'Rival 5',
    'Rival 600',
    'Prime+',
    'Prime',
    'Aerox 3',
    'Aerox 3 Wireless',
    'Aerox 3 Wireless FaZe Clan',
    'Aerox 5',
    'Aerox 5 Wireless',
    'Aerox 5 Wireless - Destiny 2',
    'Aerox 9 Wireless',
    'Aerox 9 Wireless - World of Warcraft Edition',
  ],
  downloadKeyboardList: [
    'Apex Pro Gen 3',
    'Apex Pro TKL Gen 3',
    'Apex 7',
    'Apex 9 Mini FaZe Clan',
    'Apex Pro TKL',
    'Apex 9 TKL',
    'Apex Pro Mini',
    'Apex 3',
    'Apex 3 TKL',
    'Apex 7 TKL',
    'Apex 9 Mini',
    'Apex Pro',
    'Apex 5',
  ],
};
export const uniusDownLoad: DownLoadDataRes = {
  downloadDriverUrl: '',
  downloadMouseList: [],
  downloadKeyboardList: [],
};
export const vancerDownLoad: DownLoadDataRes = {
  downloadDriverUrl: '',
  downloadMouseList: [],
  downloadKeyboardList: [],
};
export const vaxeeDownLoad: DownLoadDataRes = {
  downloadDriverUrl: '',
  downloadMouseList: [],
  downloadKeyboardList: [],
};
export const vgnDownLoad: DownLoadDataRes = {
  downloadDriverUrl: 'https://hub.vgnclub.com/home',
  downloadMouseList: ['F1 S', 'F1 Pro', 'F1 Pro Max', 'F1 Moba'],
  downloadKeyboardList: ['V98Pro V2', 'S99', 'N75 PRO', 'VXE75', 'V87', 'S87'],
};
export const waizowlDownLoad: DownLoadDataRes = {
  downloadDriverUrl: 'https://waizowl.com/zh-hant/pages/downlod',
  downloadMouseList: [
    'OGM Pro 4K',
    'OGM Pro V2',
    'OGM Cloud',
    'OGM Cloud HAWKEYE',
    'OGM ONE',
  ],
  downloadKeyboardList: [],
};
export const wlmouseDownLoad: DownLoadDataRes = {
  downloadDriverUrl: 'https://www.wlmouse.com/pages/web-hub',
  downloadMouseList: [
    'Beast Mini',
    'Beast X 8K',
    'FENZ Beast X',
    'Beast X Max',
    'Sword X',
    'Ying',
    'Beast X',
  ],
  downloadKeyboardList: [
    'Beast X Max',
    'Sword X',
    'Ying',
    'Beast Mini',
    'Beast X 8K',
    'FENZ Beast X',
  ],
};
export const keychronDownLoad: DownLoadDataRes = {
  downloadDriverUrl: '',
  downloadMouseList: [],
  downloadKeyboardList: [],
};
export const darmosharkDownLoad: DownLoadDataRes = {
  downloadDriverUrl: 'https://darmoshark.cn/qudongxiazai.html?l=EN',
  downloadMouseList: [
    'N1',
    'N1 Wireless',
    'M1',
    'M3',
    'M2 PRO',
    'M3S MAX',
    'M3',
    'M5PRO',
    'M3PRO MAX',
    'N5',
    'M5',
    'N3 PRO',
    'M3S',
    'N3',
    'M2',
    'M3 PRO',
    'M3S PRO',
    'M3S',
  ],
  downloadKeyboardList: [
    'K7',
    'K1pro',
    'KT15',
    'K7Pro',
    'Darmoshark-K3',
    'K5',
    'K3',
    'KT65 MAX',
    'TOP75',
    'K3QMK',
    'TOP87',
    'KT68 PRO',
    'EC75',
    'TOP98',
    'KT68Z',
    'SK16QMK',
    'KT68',
    'TOP75',
    'K8',
    'K9',
  ],
};
export const monkaDownLoad: DownLoadDataRes = {
  downloadDriverUrl: '',
  downloadMouseList: [],
  downloadKeyboardList: [],
};
export const mchoseDownLoad: DownLoadDataRes = {
  downloadDriverUrl: 'https://www.mchose.store/pages/firmware-2',
  downloadMouseList: [
    'A7 Series',
    'M7 Series',
    'L7 Series',
    'A5 V2 Ultra',
    'AX5 V2',
    'G7 Series',
  ],
  downloadKeyboardList: [
    'K99',
    'K99 V2',
    'G98',
    'G98 Pro',
    'K87',
    'G87',
    'GX87S',
    'KX75',
    'G75',
    'X75',
    'X75 V2',
    'Z75',
    'Z75S',
    'Ace 60/68 Series',
    'ZERO 75X',
    'Jet 75',
  ],
};
export const rapooDownLoad: DownLoadDataRes = {
  downloadDriverUrl: 'https://www.rapoo.cn/downloadcenter',
  downloadMouseList: [
    'VT3PRO',
    'VT3PRO',
    'VT1PRO MAX',
    'VT1Air MAX',
    'VT1PRO',
    'VT9PRO',
    'VT9Air',
    'VT9PRO',
    'VT9PRO MINI',
    'VT9Air Lite',
    'VT9S',
    'VT9',
    'VT3S',
    'VT960PRO',
    'VT960S',
    'VT950PRO',
    'VT950S',
    'VT350S',
    'V300PRO',
    'V300W',
    'V30W',
    'V200W',
    'V20W',
    'V20W',
    'VT30',
    'V28S',
    'V25S',
    'V22S',
    'V20S',
    'V300SE',
    'V20SE',
    'MT760NL',
    'MT760',
    'MT760 mini',
    'MT560',
    'MT550',
    'MT760L',
    'V20S',
    'V20PRO',
    'VT300',
    'V360',
    'V28S',
    'VT200',
    'V350',
    'VT960',
    'VT950Q',
    'VT950',
    'VT950C',
    'VT900',
    'VT350Q',
    'VT350',
    'VT350C',
    'VT300S',
    'VT200S',
  ],
  downloadKeyboardList: [
    'V700-8A',
    'V700DIY',
    'V700W',
    'V700V',
    'V207',
    'V700',
    'V700DIY-98',
    'V700DIY-87',
    'V700DIY-75',
    'V500PRO-87',
    'V500PRO-98',
    'V500PRO',
    'V500DIY',
    'MT510PRO',
    'V700RGB',
    'V808RGB',
    'V500RGB',
    'V708',
    'V808',
    'V500',
    'V700S',
  ],
};
export const xtrfyDownLoad: DownLoadDataRes = {
  downloadDriverUrl: 'https://cherryxtrfy.com/downloads',
  downloadMouseList: [
    'M1',
    'M1 NiP',
    'M1 RGB',
    'M2',
    'M2 NiP',
    'M3',
    'M4',
    'M4 Wireless',
    'M42',
    'M42 Wireless',
    'MZ1',
    'MZ1 Wireless',
    'M8 Wireless',
    'M64 Wireless:',
    'M68 Wireless:',
    'M64 PRO',
    'M68 PRO',
  ],
  downloadKeyboardList: [
    'K5',
    'K5V2',
    'K4',
    'K4 TKL',
    'K4 TKL LITE',
    'K3 RGB',
    'K2 RGB',
  ],
};
export const attackSharkDownLoad: DownLoadDataRes = {
  downloadDriverUrl:
    'https://attackshark.com/pages/driver-download?srsltid=AfmBOooY-IK5AConLB5K_cnBbQtSwNXYT_i9_O92MaiRLY_7Xp7kRzV-',
  downloadMouseList: [
    'X1',
    'X3',
    'X3 PRO',
    'X3 MAX',
    'X6',
    'X11',
    'R1',
    'R2',
    'R3',
    'R5 Ultra',
    'R6',
  ],
  downloadKeyboardList: [
    'K75',
    'K85',
    'K86',
    'K98 三模',
    'K98',
    'x75',
    'X85',
    'X85PRO',
    'X86',
    'X87',
    'M86',
    'X66',
    'X98PRO',
    'X68',
    'X65 Series',
  ],
};
export const valkyrieDownLoad: DownLoadDataRes = {
  downloadDriverUrl: 'https://www.valkyrie.com.cn/#/',
  downloadMouseList: ['VK M2', 'VK M1 PRO火影聯名', 'VK M1'],
  downloadKeyboardList: ['VK75', 'VK MAG75', 'VK99', 'VK87'],
};
export const razerDownLoad: DownLoadDataRes = {
  downloadDriverUrl: 'https://www.razer.com/tw-zh/synapse-4',
  downloadMouseList: [
    'D.Va Abyssus Elite',
    'Abyssus Essential',
    'Atheris',
    'Basilisk',
    'Basilisk Essential',
    'Basilisk Ultimate',
    'Basilisk V2',
    'Basilisk V3',
    'Basilisk V3 Pro',
    'Basilisk V3 X HyperSpeed',
    'Basilisk V3 35K',
    'Basilisk V3 Pro 35K',
    'Basilisk X HyperSpeed',
    'Cobra',
    'Cobra Pro',
    'DeathAdder Elite',
    'DeathAdder Essential',
    'DeathAdder V2',
    'DeathAdder V2 Mini',
    'DeathAdder V2 Pro',
    'DeathAdder V2 X HyperSpeed',
    'DeathAdder V3',
    'DeathAdder V3 HyperSpeed',
    'DeathAdder V3 Pro',
    'Lancehead',
    'Lancehead Tournament Edition',
    'Lancehead Wireless',
    'Mamba Elite',
    'Mamba Tournament Edition',
    'Mamba Wireless',
    'Naga Chroma',
    'Naga Hex V2',
    'Naga Left-Handed Edition',
    'Naga Pro',
    'Naga Trinity / Naga Classic',
    'Naga X',
    'Naga V2 HyperSpeed',
    'Naga V2 Pro',
    'Orochi V2',
    'Pro Click',
    'Pro Click Mini',
    'Turret for Xbox One',
    'Viper',
    'Viper 8KHz',
    'Viper Mini',
    'Viper Mini Signature Edition',
    'Viper Ultimate',
    'Viper V2 Pro',
    'Viper V3 HyperSpeed',
    'Viper V3 Pro',
  ],
  downloadKeyboardList: [
    'BlackWidow',
    'BlackWidow Chroma',
    'BlackWidow Chroma Tournament Edition',
    'BlackWidow Chroma V2',
    'BlackWidow Elite',
    'BlackWidow Lite',
    'BlackWidow V3',
    'BlackWidow V3 Mini HyperSpeed',
    'BlackWidow V3 Pro',
    'BlackWidow V3 Tenkeyless',
    'BlackWidow V4',
    'BlackWidow V4 Mini HyperSpeed',
    'BlackWidow V4 Pro',
    'BlackWidow V4 X',
    'BlackWidow V4 75%',
    'BlackWidow V4 Pro 75%',
    'BlackWidow X Chroma',
    'Cynosa Chroma',
    'Cynosa Chroma Pro',
    'Cynosa V2',
    'Deathstalker V2',
    'Deathstalker V2 Pro',
    'Deathstalker V2 Pro TKL',
    'Huntsman',
    'Huntsman Elite',
    'Huntsman Mini',
    'Huntsman Mini Analog',
    'Huntsman Tournament Edition',
    'Huntsman V2',
    'Huntsman V2 Analog',
    'Huntsman V2 TKL',
    'Huntsman V3 Pro',
    'Huntsman V3 Pro TKL',
    'Huntsman V3 Pro Mini',
    'Huntsman V3 X TKL',
    'Ornata Chroma',
    'Ornata V2',
    'Ornata V3',
    'Ornata V3 TKL',
    'Ornata V3 X',
    'Pro Type',
    'Pro Type Ultra',
    'Tartarus Pro',
    'Tartarus V2',
    'Turret for Xbox One',
  ],
};
export const deluxDownLoad: DownLoadDataRes = {
  downloadDriverUrl: 'https://www.deluxworld.com/service.html',
  downloadMouseList: [
    'M900mini Pro',
    'M900mini Ultra',
    'M900PRO+',
    'M700pro+',
    'M700Ultra',
    'M600Ultra',
    'M900pro',
    'M900minipro',
    'M800pro',
    'M700pro',
    'M600pro',
    'M500pro',
    'M500',
    'M800Ultra',
    'M800pro',
    'M618mini',
    'M618mini DB',
    'M625',
    'M618Plus',
    'M912',
    'M631',
    'M820',
    'M618XSU',
    'M618XSD',
    'M618V',
    'M629BU',
    'M629BU',
    'M629DB',
    'M800BU',
    'M618',
    'M800',
    'M800DB',
    'M800BU',
    'M700BU',
    'M700BU',
    'M800DB',
    'MT1',
    'M628',
    'M618X',
    'M618X Wireless',
    'M522GL 雙模',
    'M627',
    'M627S',
    'M618PLUS',
  ],
  downloadKeyboardList: [
    'KM87',
    'KM18',
    'KM17',
    'KM18DB',
    'KM17',
    'KS200 三模',
    'KS100 設計師',
    'T9X',
    'T9plus',
    'T9plus',
    'T11',
    'KM9028',
    'KM09',
    'KM08',
    'KM06',
    'KM02',
    'KM13',
  ],
};
export const atkDownLoad: DownLoadDataRes = {
  downloadDriverUrl:
    'https://www.atk.store/pages/atk-hub?srsltid=AfmBOoqvbEEeRWCNKUonTWYwitUtt2I0vS0hb_3cSklrh-ker5uQaear',
  downloadMouseList: [
    'Blazing Sky F1',
    'Blazing Sky X1',
    'Blazing Sky Z1',
    'Blazing Sky F1 LEVIATAN Collaboration',
  ],
  downloadKeyboardList: [
    'ATK RS6 Aluminum Hall Effect',
    'EDGE 60 HE',
    'ATK 68 V2',
    'ATK RS7',
    'ATK VXE V75X',
    'ATK VXE V75K',
    'ATK Z87',
    'ATK V100',
  ],
};
export const madLionsDownLoad: DownLoadDataRes = {
  downloadDriverUrl: '',
  downloadMouseList: [],
  downloadKeyboardList: [],
};
export const akkoDownLoad: DownLoadDataRes = {
  downloadDriverUrl: '',
  downloadMouseList: [],
  downloadKeyboardList: ['5108B'],
};
export const aulaDownLoad: DownLoadDataRes = {
  downloadDriverUrl:
    'https://drive.google.com/drive/folders/18Jd6EEPT_U0MugJHM3-x84dD20fio9w0',
  downloadMouseList: [
    'T201',
    'AULA T102M',
    'AULA T102',
    'AULA SC800',
    'AULA SC800 8KReceiver',
    'AULA SC660',
    'AULA SC580',
    'AULA SC400',
    'AULA S100',
    'AULA S100Pro',
    'AULA S80',
    'AULA S50',
    'AULA S30',
    'AULA S22',
    'AULA S20',
    'AULA S18',
    'AULA S12Pro Wired',
    'AULA H512',
    'AULA H510',
  ],
  downloadKeyboardList: [
    'S98PRO',
    'F108pro',
    'F108',
    'F108',
    'F65',
    'T201',
    'AULA T102M',
    'AULA T102',
    'AULA S2022',
    'AULA S99 Pro',
    'AULA S99',
    'AULA S98 Pro',
    'AULA S98 Wired',
    'AULA S98 三模',
    'AULA M75',
    'AULA L2098',
    'AULA L87',
    'AULA Hi98',
    'AULA HI75',
    'AULA Hi8SE',
    'AULA FAULA 3032 Wired RGB',
    'AULA F3680',
    'AULA F3287',
    'AULA F3287',
    'AULA F3268 Wired',
    'AULA F3261',
    'AULA F3087',
    'AULA F3068',
    'AULA F3060',
    'AULA F3050',
  ],
};
export const dareuDownLoad: DownLoadDataRes = {
  downloadDriverUrl: 'https://cn.dareu.com/?m=home&c=Lists&a=index&tid=64',
  downloadMouseList: [
    'V98Pro V2',
    'S99',
    'N75 PRO',
    'VXE75',
    'V87',
    'S87',
    'A950Air',
    'A950Air 蟬翼',
    'A950Air 電擎版',
    'A980Pro',
    'A980ProMax',
    'A980Pro 電擎版',
    'A950Pro',
    'A950Pro 鎂合金',
    'LM129',
  ],
  downloadKeyboardList: [
    'A75HE',
    'EK75RT',
    'A98專業版',
    'Ek87Pro',
    'EK75',
    'A104PRO',
    'A81',
  ],
};
export const gravaStarDownLoad: DownLoadDataRes = {
  downloadDriverUrl:
    'https://www.gravastar.com/pages/download?srsltid=AfmBOoozm81fD9JCGVdf1W39cRRIrsoW7t9liqTdhLTJgoLJvfyqTSGm',
  downloadMouseList: [
    'Mercury X Pro 8K Wireless',
    'Mercury X Wireless',
    'Mercury X & X Pro Battle Worn-Yellow',
    'Mercury M1 Pro Gunmetal Gray',
    'Mercury M1 Pro Gradient Black',
    'Mercury M2 - Stealth Black',
    'Mercury M2 - Transparent Black',
    'Mercury M1 Pro Battle Worn Edition-Silver Mist',
  ],
  downloadKeyboardList: [
    'Mercury K1 Pro Special Edition - Cyberpunk',
    'Mercury K1 Pro - Galaxy Black',
    'Mercury K1 Pro Battle-Worn Yellow',
    'Mercury K1 Pro - Silver Gray',
    'Mercury K1 - Gradient Black',
    'Mercury K1 Lite - Transparent Black',
    'Mercury K1 - Gradient White',
    'Mercury K1 Lite - Snow White',
  ],
};
