import { mouseDriverViewRes } from '../../../types/mouseDriverView/res/mouseDriverViewRes';

export const data: mouseDriverViewRes[] = [
  {
    id: '1',
    img: 'images/Lamzu.jpg',
    englishName: 'Lamzu',
    chineseName: '蘭族',
    downloadDriverUrl:
      'https://lamzu.com/pages/download?srsltid=AfmBOoqn-vbEhqAn4GgWbRf8C2CZZqKZac_is0IOJq4GOeqQlZFUuXKv',
    downloadMouseList: [
      'Atlantis OG V1 & V2',
      'Atlantis OG V2 PRO',
      'Atlantis OG V2 4K',
      'Atlantis MINI',
      'Atlantis MINI PRO',
      'Atlantis MINI 4K',
      'Atlantis MINI Champion Edition',
      'THORN(4K Compatible)',
      'THORN 4K',
      'LAMZU X FNATIC THORN 4K',
      'MAYA(4K Compatible)',
      'MAYA 4K',
      'MAYA Doodle',
      'LAMZU X FNATIC MAYA 8K',
      'LAMZU X FNATIC MAYA X 8K',
      'MAYA X 8K',
      'Paro',
      'Tachi',
      'Inca',
      'Atlantis OG V1 & V2',
      'Atlantis OG V2 PRO',
      'Atlantis OG V2 4K',
      'Atlantis MINI',
      'Atlantis MINI PRO',
      'Atlantis MINI 4K',
      'Atlantis MINI Champion Edition',
      'THORN(4K Compatible)',
      'THORN 4K',
      'LAMZU X FNATIC THORN 4K',
      'MAYA(4K Compatible)',
      'MAYA 4K',
      'MAYA Doodle',
      'LAMZU X FNATIC MAYA 8K',
      'LAMZU X FNATIC MAYA X 8K',
      'MAYA X 8K',
      'Paro',
      'Tachi',
      'Inca',
    ],
    downloadKeyboardList: [],
    webDriverUrl: 'https://www.lamzu.net/#/project/items',
    webMouseList: [
      'Tachi',
      'Inca',
      'MAYA X 8K',
      'LAMZU X FNATIC MAYA 8K',
      'LAMZU X FNATIC MAYA X 8K',
      'Tachi',
      'Inca',
      'MAYA X 8K',
      'LAMZU X FNATIC MAYA 8K',
      'LAMZU X FNATIC MAYA X 8K',
    ],
    webKeyboardList: [],
  },
  {
    id: '2',
    img: 'images/Ninjutso.jpg',
    englishName: 'Ninjutso',
    chineseName: '',
    downloadDriverUrl: '',
    downloadMouseList: [],
    downloadKeyboardList: [],
    webDriverUrl: '',
    webMouseList: [],
    webKeyboardList: [],
  },
  {
    id: '3',
    img: 'images/Ajazz.jpg',
    englishName: 'Ajazz',
    chineseName: '黑爵',
    downloadDriverUrl: '',
    downloadMouseList: [],
    downloadKeyboardList: [],
    webDriverUrl: '',
    webMouseList: [],
    webKeyboardList: [],
  },
  {
    id: '4',
    img: 'images/BloodyGaming.png',
    englishName: 'Bloody Gaming',
    chineseName: '血手幽靈',
    downloadDriverUrl: '',
    downloadMouseList: [],
    downloadKeyboardList: [],
    webDriverUrl: '',
    webMouseList: [],
    webKeyboardList: [],
  },
  {
    id: '5',
    img: 'images/CoolerMaster.jpg',
    englishName: 'CoolerMaster',
    chineseName: '酷碼',
    downloadDriverUrl: '',
    downloadMouseList: [],
    downloadKeyboardList: [],
    webDriverUrl: '',
    webMouseList: [],
    webKeyboardList: [],
  },
  {
    id: '6',
    img: 'images/Corsair.png',
    englishName: 'Corsair',
    chineseName: '海盜船',
    downloadDriverUrl: '',
    downloadMouseList: [],
    downloadKeyboardList: [],
    webDriverUrl: '',
    webMouseList: [],
    webKeyboardList: [],
  },
  {
    id: '7',
    img: 'images/LogitechG.png',
    englishName: 'Logitech G',
    chineseName: '羅技',
    downloadDriverUrl: '',
    downloadMouseList: [],
    downloadKeyboardList: [],
    webDriverUrl: '',
    webMouseList: [],
    webKeyboardList: [],
  },
  {
    id: '8',
    img: 'images/Cougar.png',
    englishName: 'Cougar',
    chineseName: '美洲獅',
    downloadDriverUrl: '',
    downloadMouseList: [],
    downloadKeyboardList: [],
    webDriverUrl: '',
    webMouseList: [],
    webKeyboardList: [],
  },
  {
    id: '9',
    img: 'images/EndgameGear.png',
    englishName: 'Endgame Gear',
    chineseName: '',
    downloadDriverUrl: '',
    downloadMouseList: [],
    downloadKeyboardList: [],
    webDriverUrl: '',
    webMouseList: [],
    webKeyboardList: [],
  },
  {
    id: '10',
    img: 'images/Finalmouse.png',
    englishName: 'Finalmouse',
    chineseName: '',
    downloadDriverUrl: '',
    downloadMouseList: [],
    downloadKeyboardList: [],
    webDriverUrl: '',
    webMouseList: [],
    webKeyboardList: [],
  },
  {
    id: '11',
    img: 'images/Fnatic.png',
    englishName: 'Fnatic',
    chineseName: '',
    downloadDriverUrl: '',
    downloadMouseList: [],
    downloadKeyboardList: [],
    webDriverUrl: '',
    webMouseList: [],
    webKeyboardList: [],
  },
  {
    id: '12',
    img: 'images/G-Wolves.png',
    englishName: 'G - Wolves',
    chineseName: '遊狼',
    downloadDriverUrl: '',
    downloadMouseList: [],
    downloadKeyboardList: [],
    webDriverUrl: '',
    webMouseList: [],
    webKeyboardList: [],
  },
  {
    id: '13',
    img: 'images/Glorious.png',
    englishName: 'Glorious',
    chineseName: '',
    downloadDriverUrl: '',
    downloadMouseList: [],
    downloadKeyboardList: [],
    webDriverUrl: '',
    webMouseList: [],
    webKeyboardList: [],
  },
  {
    id: '14',
    img: 'images/Hitscan.png',
    englishName: 'Hitscan',
    chineseName: '',
    downloadDriverUrl: '',
    downloadMouseList: [],
    downloadKeyboardList: [],
    webDriverUrl: '',
    webMouseList: [],
    webKeyboardList: [],
  },
  {
    id: '15',
    img: 'images/HyperX.png',
    englishName: 'HyperX',
    chineseName: '',
    downloadDriverUrl: '',
    downloadMouseList: [],
    downloadKeyboardList: [],
    webDriverUrl: '',
    webMouseList: [],
    webKeyboardList: [],
  },
  {
    id: '16',
    img: 'images/Incott.png',
    englishName: 'Incott',
    chineseName: '因科特',
    downloadDriverUrl: '',
    downloadMouseList: [],
    downloadKeyboardList: [],
    webDriverUrl: '',
    webMouseList: [],
    webKeyboardList: [],
  },
  {
    id: '17',
    img: 'images/IPI.png',
    englishName: 'IPI',
    chineseName: '',
    downloadDriverUrl: '',
    downloadMouseList: [],
    downloadKeyboardList: [],
    webDriverUrl: '',
    webMouseList: [],
    webKeyboardList: [],
  },
  {
    id: '18',
    img: 'images/Irocks.png',
    englishName: 'Irocks',
    chineseName: '艾芮克',
    downloadDriverUrl: '',
    downloadMouseList: [],
    downloadKeyboardList: [],
    webDriverUrl: '',
    webMouseList: [],
    webKeyboardList: [],
  },
  {
    id: '19',
    img: 'images/NZXT.png',
    englishName: 'NZXT',
    chineseName: '恩傑',
    downloadDriverUrl: '',
    downloadMouseList: [],
    downloadKeyboardList: [],
    webDriverUrl: '',
    webMouseList: [],
    webKeyboardList: [],
  },
  {
    id: '20',
    img: 'images/Pulsar.png',
    englishName: 'Pulsar',
    chineseName: '派世',
    downloadDriverUrl: '',
    downloadMouseList: [],
    downloadKeyboardList: [],
    webDriverUrl: '',
    webMouseList: [],
    webKeyboardList: [],
  },
  {
    id: '21',
    img: 'images/TurtleRoccat.png',
    englishName: 'TurtleBeach & Roccat',
    chineseName: '',
    downloadDriverUrl: '',
    downloadMouseList: [],
    downloadKeyboardList: [],
    webDriverUrl: '',
    webMouseList: [],
    webKeyboardList: [],
  },
  {
    id: '22',
    img: 'images/ROG.png',
    englishName: 'ROG',
    chineseName: '華碩',
    downloadDriverUrl: '',
    downloadMouseList: [],
    downloadKeyboardList: [],
    webDriverUrl: '',
    webMouseList: [],
    webKeyboardList: [],
  },
  {
    id: '23',
    img: 'images/TUF.png',
    englishName: 'TUF',
    chineseName: '華碩',
    downloadDriverUrl: '',
    downloadMouseList: [],
    downloadKeyboardList: [],
    webDriverUrl: '',
    webMouseList: [],
    webKeyboardList: [],
  },
  {
    id: '24',
    img: 'images/Steelseries.png',
    englishName: 'Steelseries',
    chineseName: '賽睿',
    downloadDriverUrl: '',
    downloadMouseList: [],
    downloadKeyboardList: [],
    webDriverUrl: '',
    webMouseList: [],
    webKeyboardList: [],
  },
  {
    id: '25',
    img: 'images/Unius.png',
    englishName: 'Unius',
    chineseName: '',
    downloadDriverUrl: '',
    downloadMouseList: [],
    downloadKeyboardList: [],
    webDriverUrl: '',
    webMouseList: [],
    webKeyboardList: [],
  },
  {
    id: '26',
    img: 'images/Vancer.png',
    englishName: 'Vancer',
    chineseName: '',
    downloadDriverUrl: '',
    downloadMouseList: [],
    downloadKeyboardList: [],
    webDriverUrl: '',
    webMouseList: [],
    webKeyboardList: [],
  },
  {
    id: '27',
    img: 'images/Vaxee.png',
    englishName: 'Vaxee',
    chineseName: '',
    downloadDriverUrl: '',
    downloadMouseList: [],
    downloadKeyboardList: [],
    webDriverUrl: '',
    webMouseList: [],
    webKeyboardList: [],
  },
  {
    id: '28',
    img: 'images/VGN.png',
    englishName: 'VGN',
    chineseName: '',
    downloadDriverUrl: '',
    downloadMouseList: [],
    downloadKeyboardList: [],
    webDriverUrl: '',
    webMouseList: [],
    webKeyboardList: [],
  },
  {
    id: '29',
    img: 'images/Waizowl.png',
    englishName: 'Waizowl',
    chineseName: '唯卓',
    downloadDriverUrl: '',
    downloadMouseList: [],
    downloadKeyboardList: [],
    webDriverUrl: '',
    webMouseList: [],
    webKeyboardList: [],
  },
  {
    id: '30',
    img: 'images/WLmouse.png',
    englishName: 'WLmouse',
    chineseName: '萬靈',
    downloadDriverUrl: '',
    downloadMouseList: [],
    downloadKeyboardList: [],
    webDriverUrl: '',
    webMouseList: [],
    webKeyboardList: [],
  },
  {
    id: '31',
    img: 'images/Keychron.png',
    englishName: 'Keychron',
    chineseName: '渴創',
    downloadDriverUrl: '',
    downloadMouseList: [],
    downloadKeyboardList: [],
    webDriverUrl: '',
    webMouseList: [],
    webKeyboardList: [],
  },
  {
    id: '32',
    img: 'images/Darmoshark.png',
    englishName: 'Darmoshark',
    chineseName: '達摩鯊',
    downloadDriverUrl: '',
    downloadMouseList: [],
    downloadKeyboardList: [],
    webDriverUrl: '',
    webMouseList: [],
    webKeyboardList: [],
  },
  {
    id: '33',
    img: 'images/Monka.png',
    englishName: 'Monka',
    chineseName: '魔咖',
    downloadDriverUrl: '',
    downloadMouseList: [],
    downloadKeyboardList: [],
    webDriverUrl: '',
    webMouseList: [],
    webKeyboardList: [],
  },
  {
    id: '34',
    img: 'images/MCHOSE.png',
    englishName: 'MCHOSE',
    chineseName: '邁從',
    downloadDriverUrl: '',
    downloadMouseList: [],
    downloadKeyboardList: [],
    webDriverUrl: '',
    webMouseList: [],
    webKeyboardList: [],
  },
  {
    id: '35',
    img: 'images/Rapoo.png',
    englishName: 'Rapoo',
    chineseName: '雷柏',
    downloadDriverUrl: '',
    downloadMouseList: [],
    downloadKeyboardList: [],
    webDriverUrl: '',
    webMouseList: [],
    webKeyboardList: [],
  },
  {
    id: '36',
    img: 'images/XTRFY.png',
    englishName: 'XTRFY',
    chineseName: '',
    downloadDriverUrl: '',
    downloadMouseList: [],
    downloadKeyboardList: [],
    webDriverUrl: '',
    webMouseList: [],
    webKeyboardList: [],
  },
  {
    id: '37',
    img: 'images/ATTACK SHARK.png',
    englishName: 'ATTACK SHARK',
    chineseName: '攻擊鯊',
    downloadDriverUrl: '',
    downloadMouseList: [],
    downloadKeyboardList: [],
    webDriverUrl: '',
    webMouseList: [],
    webKeyboardList: [],
  },
  {
    id: '39',
    img: 'images/VALKYRIE.png',
    englishName: 'VALKYRIE',
    chineseName: '瓦爾基里',
    downloadDriverUrl: '',
    downloadMouseList: [],
    downloadKeyboardList: [],
    webDriverUrl: '',
    webMouseList: [],
    webKeyboardList: [],
  },
  {
    id: '40',
    img: 'images/Razer.png',
    englishName: 'Razer',
    chineseName: '雷蛇',
    downloadDriverUrl: '',
    downloadMouseList: [],
    downloadKeyboardList: [],
    webDriverUrl: '',
    webMouseList: [],
    webKeyboardList: [],
  },
  {
    id: '',
    img: 'images/Delux.png',
    englishName: 'Delux',
    chineseName: '多彩',
    downloadDriverUrl: '',
    downloadMouseList: [],
    downloadKeyboardList: [],
    webDriverUrl: '',
    webMouseList: [],
    webKeyboardList: [],
  },
  {
    id: '',
    img: 'images/ATK.png',
    englishName: 'ATK',
    chineseName: '',
    downloadDriverUrl: '',
    downloadMouseList: [],
    downloadKeyboardList: [],
    webDriverUrl: '',
    webMouseList: [],
    webKeyboardList: [],
  },
  {
    id: '',
    img: 'images/MADLIONS.png',
    englishName: 'MADLIONS',
    chineseName: '美加獅',
    downloadDriverUrl: '',
    downloadMouseList: [],
    downloadKeyboardList: [],
    webDriverUrl: '',
    webMouseList: [],
    webKeyboardList: [],
  },
  {
    id: '',
    img: 'images/Akko.png',
    englishName: 'Akko',
    chineseName: '艾酷',
    downloadDriverUrl: '',
    downloadMouseList: [],
    downloadKeyboardList: [],
    webDriverUrl: '',
    webMouseList: [],
    webKeyboardList: [],
  },
  {
    id: '',
    img: 'images/AULA.png',
    englishName: 'AULA',
    chineseName: '狼蛛',
    downloadDriverUrl: '',
    downloadMouseList: [],
    downloadKeyboardList: [],
    webDriverUrl: '',
    webMouseList: [],
    webKeyboardList: [],
  },
  {
    id: '',
    img: 'images/Dareu.png',
    englishName: 'Dareu',
    chineseName: '達爾優',
    downloadDriverUrl: '',
    downloadMouseList: [],
    downloadKeyboardList: [],
    webDriverUrl: '',
    webMouseList: [],
    webKeyboardList: [],
  },
  {
    id: '',
    img: 'images/GravaStar.png',
    englishName: 'GravaStar',
    chineseName: '重力星球',
    downloadDriverUrl: '',
    downloadMouseList: [],
    downloadKeyboardList: [],
    webDriverUrl: '',
    webMouseList: [],
    webKeyboardList: [],
},
];


