export const data = [
  {
    id: '1',
    img: 'images/Lamzu.jpg',
    englishName: 'Lamzu',
    chineseName: '蘭族',
  },
  {
    id: '2',
    img: 'images/Ninjutso.jpg',
    englishName: 'Ninjutso',
    chineseName: '',
  },
  {
    id: '3',
    img: 'images/Ajazz.jpg',
    englishName: 'Ajazz',
    chineseName: '黑爵',
  },
  {
    id: '4',
    img: 'images/BloodyGaming.png',
    englishName: 'Bloody Gaming',
    chineseName: '血手幽靈',
  },
  {
    id: '5',
    img: 'images/CoolerMaster.jpg',
    englishName: 'CoolerMaster',
    chineseName: '酷碼',
  },
  {
    id: '6',
    img: 'images/Corsair.png',
    englishName: 'Corsair',
    chineseName: '海盜船',
  },
  {
    id: '7',
    img: 'images/LogitechG.png',
    englishName: 'Logitech G',
    chineseName: '羅技',
  },
  {
    id: '8',
    img: 'images/Cougar.png',
    englishName: 'Cougar',
    chineseName: '美洲獅',
  },
  {
    id: '9',
    img: 'images/EndgameGear.png',
    englishName: 'Endgame Gear',
    chineseName: '',
  },
  {
    id: '10',
    img: 'images/Finalmouse.png',
    englishName: 'Finalmouse',
    chineseName: '',
  },
  {
    id: '11',
    img: 'images/Fnatic.png',
    englishName: 'Fnatic',
    chineseName: '',
  },
  {
    id: '12',
    img: 'images/G-Wolves.png',
    englishName: 'G - Wolves',
    chineseName: '遊狼',
  },
  {
    id: '13',
    img: 'images/Glorious.png',
    englishName: 'Glorious',
    chineseName: '',
  },
  {
    id: '14',
    img: 'images/Hitscan.png',
    englishName: 'Hitscan',
    chineseName: '',
  },
  {
    id: '15',
    img: 'images/HyperX.png',
    englishName: 'HyperX',
    chineseName: '',
  },
  {
    id: '16',
    img: 'images/Incott.png',
    englishName: 'Incott',
    chineseName: '因科特',
  },
  {
    id: '17',
    img: 'images/IPI.png',
    englishName: 'IPI',
    chineseName: '',
  },
];
